FROM python:3.11-slim

# Минимальные зависимости (как в Lab 3)
RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Используем ОТДЕЛЬНЫЙ requirements файл для Lab 4
COPY requirements-lab4.txt .
RUN pip install --no-cache-dir -r requirements-lab4.txt

# Копируем код
COPY . .

# Создаем папку для данных
RUN mkdir -p /app/data

EXPOSE 8181

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8181"]
